/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsVersionsDotjsonRouteImport } from './routes/docs/versions[.]json'
import { Route as DocsRoutesDotjsonRouteImport } from './routes/docs/routes[.]json'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsCanaryRoutesDotjsonRouteImport } from './routes/docs/canary/routes[.]json'
import { Route as DocsVersionRoutesDotjsonRouteImport } from './routes/docs/$version/routes[.]json'
import { Route as ApiSearchVersionRouteImport } from './routes/api/search/$version'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsVersionsDotjsonRoute = DocsVersionsDotjsonRouteImport.update({
  id: '/docs/versions.json',
  path: '/docs/versions.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoutesDotjsonRoute = DocsRoutesDotjsonRouteImport.update({
  id: '/docs/routes.json',
  path: '/docs/routes.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCanaryRoutesDotjsonRoute = DocsCanaryRoutesDotjsonRouteImport.update({
  id: '/docs/canary/routes.json',
  path: '/docs/canary/routes.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsVersionRoutesDotjsonRoute =
  DocsVersionRoutesDotjsonRouteImport.update({
    id: '/docs/$version/routes.json',
    path: '/docs/$version/routes.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSearchVersionRoute = ApiSearchVersionRouteImport.update({
  id: '/api/search/$version',
  path: '/api/search/$version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/routes.json': typeof DocsRoutesDotjsonRoute
  '/docs/versions.json': typeof DocsVersionsDotjsonRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/api/search/$version': typeof ApiSearchVersionRoute
  '/docs/$version/routes.json': typeof DocsVersionRoutesDotjsonRoute
  '/docs/canary/routes.json': typeof DocsCanaryRoutesDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/routes.json': typeof DocsRoutesDotjsonRoute
  '/docs/versions.json': typeof DocsVersionsDotjsonRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/api/search/$version': typeof ApiSearchVersionRoute
  '/docs/$version/routes.json': typeof DocsVersionRoutesDotjsonRoute
  '/docs/canary/routes.json': typeof DocsCanaryRoutesDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/routes.json': typeof DocsRoutesDotjsonRoute
  '/docs/versions.json': typeof DocsVersionsDotjsonRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/api/search/$version': typeof ApiSearchVersionRoute
  '/docs/$version/routes.json': typeof DocsVersionRoutesDotjsonRoute
  '/docs/canary/routes.json': typeof DocsCanaryRoutesDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/docs/$'
    | '/docs/routes.json'
    | '/docs/versions.json'
    | '/docs/{$}.md'
    | '/api/search/$version'
    | '/docs/$version/routes.json'
    | '/docs/canary/routes.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/docs/$'
    | '/docs/routes.json'
    | '/docs/versions.json'
    | '/docs/{$}.md'
    | '/api/search/$version'
    | '/docs/$version/routes.json'
    | '/docs/canary/routes.json'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/docs/$'
    | '/docs/routes.json'
    | '/docs/versions.json'
    | '/docs/{$}.md'
    | '/api/search/$version'
    | '/docs/$version/routes.json'
    | '/docs/canary/routes.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsRoutesDotjsonRoute: typeof DocsRoutesDotjsonRoute
  DocsVersionsDotjsonRoute: typeof DocsVersionsDotjsonRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  ApiSearchVersionRoute: typeof ApiSearchVersionRoute
  DocsVersionRoutesDotjsonRoute: typeof DocsVersionRoutesDotjsonRoute
  DocsCanaryRoutesDotjsonRoute: typeof DocsCanaryRoutesDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/versions.json': {
      id: '/docs/versions.json'
      path: '/docs/versions.json'
      fullPath: '/docs/versions.json'
      preLoaderRoute: typeof DocsVersionsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/routes.json': {
      id: '/docs/routes.json'
      path: '/docs/routes.json'
      fullPath: '/docs/routes.json'
      preLoaderRoute: typeof DocsRoutesDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/canary/routes.json': {
      id: '/docs/canary/routes.json'
      path: '/docs/canary/routes.json'
      fullPath: '/docs/canary/routes.json'
      preLoaderRoute: typeof DocsCanaryRoutesDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$version/routes.json': {
      id: '/docs/$version/routes.json'
      path: '/docs/$version/routes.json'
      fullPath: '/docs/$version/routes.json'
      preLoaderRoute: typeof DocsVersionRoutesDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/$version': {
      id: '/api/search/$version'
      path: '/api/search/$version'
      fullPath: '/api/search/$version'
      preLoaderRoute: typeof ApiSearchVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsRoutesDotjsonRoute: DocsRoutesDotjsonRoute,
  DocsVersionsDotjsonRoute: DocsVersionsDotjsonRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  ApiSearchVersionRoute: ApiSearchVersionRoute,
  DocsVersionRoutesDotjsonRoute: DocsVersionRoutesDotjsonRoute,
  DocsCanaryRoutesDotjsonRoute: DocsCanaryRoutesDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
