/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeAudioSourceHandle {
  get track(): NativeMediaStreamTrack
  get sampleRate(): number
  get channels(): number
  get queuedDuration(): number
  captureFrame(data: Int16Array, sampleRate: number, channels: number, samplesPerChannel: number): Promise<void>
  waitForPlayout(): Promise<void>
  clearQueue(): void
  close(): void
}

export declare class NativeAudioStreamHandle {
  get droppedFrames(): bigint
  nextFrame(): Promise<NativeAudioFrame | null>
  close(): void
}

export declare class NativeDataChannel {
  get droppedEvents(): bigint
  get queueTerminalReason(): string | null
  get id(): number
  get label(): string
  get readyState(): string
  get bufferedAmount(): number
  get ordered(): boolean
  get negotiated(): boolean
  get protocol(): string
  send(data: Uint8Array, binary: boolean): void
  nextEvent(): Promise<NativeDataChannelEvent | null>
  close(): void
}

export declare class NativeGenerationBudget {
  get reservedBytes(): bigint
  get saturations(): bigint
  close(): void
}

export declare class NativeMediaStream {
  get id(): string
  getAudioTracks(): Array<NativeMediaStreamTrack>
  getVideoTracks(): Array<NativeMediaStreamTrack>
}

export declare class NativeMediaStreamTrack {
  get identity(): bigint
  get id(): string
  get kind(): string
  get enabled(): boolean
  set enabled(enabled: boolean)
  get readyState(): string
  stop(): void
}

export declare class NativePeerConnection {
  get droppedEvents(): bigint
  get queueTerminalReason(): string | null
  get connectionState(): string
  get signalingState(): string
  get iceConnectionState(): string
  get localDescription(): NativeSessionDescription | null
  get remoteDescription(): NativeSessionDescription | null
  get currentLocalDescription(): NativeSessionDescription | null
  get currentRemoteDescription(): NativeSessionDescription | null
  getConfiguration(): NativeRtcConfiguration
  setConfiguration(configuration: NativeRtcConfiguration): void
  createOffer(options?: NativeOfferOptions | undefined | null): Promise<NativeSessionDescription>
  createAnswer(): Promise<NativeSessionDescription>
  setLocalDescription(description: NativeSessionDescription): Promise<void>
  setRemoteDescription(description: NativeSessionDescription): Promise<void>
  addIceCandidate(candidate?: NativeIceCandidate | undefined | null): Promise<void>
  createDataChannel(label: string, options?: NativeDataChannelOptions | undefined | null): NativeDataChannel
  addTrack(track: NativeMediaStreamTrack, streamIds: Array<string>): NativeRtpSender
  removeTrack(sender: NativeRtpSender): void
  addTransceiver(trackOrKind: NativeMediaStreamTrack, direction?: string | undefined | null, streamIds?: Array<string> | undefined | null, sendEncodings?: Array<NativeRtpEncodingParameters> | undefined | null): NativeRtpTransceiver
  addTransceiverForKind(kind: string, direction?: string | undefined | null, streamIds?: Array<string> | undefined | null, sendEncodings?: Array<NativeRtpEncodingParameters> | undefined | null): NativeRtpTransceiver
  getSenders(): Array<NativeRtpSender>
  getReceivers(): Array<NativeRtpReceiver>
  getTransceivers(): Array<NativeRtpTransceiver>
  restartIce(): void
  getStats(): Promise<string>
  nextEvent(): Promise<NativePeerEvent | null>
  takeTrackEvent(handle: number): NativeTrackEvent
  takeDataChannel(handle: number): NativeDataChannel
  close(): void
}

export declare class NativeRtcEngine {
  constructor(options?: NativeRtcEngineOptions | undefined | null)
  close(): void
  createGenerationBudget(maxQueuedBytes: number): NativeGenerationBudget
  get reservedBytes(): bigint
  get queueSaturations(): bigint
  createPeerConnection(configuration: NativeRtcConfiguration | undefined | null, budget: NativeGenerationBudget): NativePeerConnection
  createAudioSource(options: NativeAudioSourceOptions | undefined | null, budget: NativeGenerationBudget): NativeAudioSourceHandle
  createAudioStream(track: NativeMediaStreamTrack, options: NativeAudioStreamOptions | undefined | null, budget: NativeGenerationBudget): NativeAudioStreamHandle
  createVideoSource(options: NativeVideoSourceOptions, budget: NativeGenerationBudget): NativeVideoSourceHandle
  createVideoStream(track: NativeMediaStreamTrack, options: NativeVideoStreamOptions | undefined | null, budget: NativeGenerationBudget): NativeVideoStreamHandle
  cloneTrack(track: NativeMediaStreamTrack): NativeMediaStreamTrack
  getRtpSenderCapabilities(kind: string): NativeRtpCapabilities
  getRtpReceiverCapabilities(kind: string): NativeRtpCapabilities
}

export declare class NativeRtpReceiver {
  get identity(): bigint
  get track(): NativeMediaStreamTrack | null
  getParameters(): NativeRtpParameters
  getStats(): Promise<string>
}

export declare class NativeRtpSender {
  get identity(): bigint
  get track(): NativeMediaStreamTrack | null
  replaceTrack(track?: NativeMediaStreamTrack | undefined | null): void
  getParameters(): NativeRtpParameters
  setParameters(parameters: NativeRtpParameters): void
  getStats(): Promise<string>
}

export declare class NativeRtpTransceiver {
  get identity(): bigint
  get mid(): string | null
  get direction(): string
  set direction(value: string)
  get currentDirection(): string | null
  get sender(): NativeRtpSender
  get receiver(): NativeRtpReceiver
  setCodecPreferences(codecs: Array<NativeRtpCodecCapability>): void
  stop(): void
}

export declare class NativeTrackEvent {
  get track(): NativeMediaStreamTrack
  get receiver(): NativeRtpReceiver
  get transceiver(): NativeRtpTransceiver
  get streams(): Array<NativeMediaStream>
}

export declare class NativeVideoSourceHandle {
  get track(): NativeMediaStreamTrack
  get width(): number
  get height(): number
  captureFrame(data: Uint8Array, width: number, height: number, timestampUs: bigint, rotation: number): void
  close(): void
}

export declare class NativeVideoStreamHandle {
  get droppedFrames(): bigint
  nextFrame(): Promise<NativeVideoFrameEvent | null>
  close(): void
}

export declare function nativeAbiVersion(): number

export interface NativeAudioFrame {
  data: Int16Array
  sampleRate: number
  channels: number
  samplesPerChannel: number
}

export interface NativeAudioSourceOptions {
  label?: string
  sampleRate?: number
  channels?: number
  queueSizeMs?: number
  echoCancellation?: boolean
  noiseSuppression?: boolean
  autoGainControl?: boolean
}

export interface NativeAudioStreamOptions {
  sampleRate?: number
  channels?: number
  queueSizeFrames?: number
}

export interface NativeDataChannelEvent {
  kind: string
  state?: string
  data?: Uint8Array
  binary?: boolean
}

export interface NativeDataChannelOptions {
  ordered?: boolean
  maxPacketLifeTime?: number
  maxRetransmits?: number
  protocol?: string
  negotiated?: boolean
  id?: number
}

export interface NativeIceCandidate {
  candidate: string
  sdpMid: string
  sdpMLineIndex: number
}

export interface NativeIceServer {
  urls: Array<string>
  username?: string
  credential?: string
}

export interface NativeOfferOptions {
  iceRestart?: boolean
  offerToReceiveAudio?: boolean
  offerToReceiveVideo?: boolean
}

export interface NativePeerEvent {
  kind: string
  state?: string
  candidate?: NativeIceCandidate
  handle?: number
  address?: string
  port?: number
  url?: string
  errorCode?: number
  errorText?: string
}

export interface NativeRtcConfiguration {
  iceServers?: Array<NativeIceServer>
  iceTransportPolicy?: string
  minPort?: number
  maxPort?: number
  iceConnectionReceivingTimeoutMs?: number
  iceBackupCandidatePairPingIntervalMs?: number
  iceCheckIntervalStrongConnectivityMs?: number
  iceCheckIntervalWeakConnectivityMs?: number
  iceCheckMinIntervalMs?: number
  iceUnwritableTimeoutMs?: number
  iceInactiveTimeoutMs?: number
  stunCandidateKeepaliveIntervalMs?: number
}

export interface NativeRtcEngineOptions {
  ignoredInterfaces?: Array<string>
  ignoredAdapterTypes?: Array<string>
  maxQueuedBytes?: number
}

export interface NativeRtcpParameters {
  cname?: string
  reducedSize?: boolean
}

export interface NativeRtpCapabilities {
  codecs: Array<NativeRtpCodecCapability>
  headerExtensions: Array<NativeRtpHeaderExtensionCapability>
}

export interface NativeRtpCodecCapability {
  mimeType: string
  clockRate: number
  channels?: number
  sdpFmtpLine?: string
}

export interface NativeRtpCodecParameters {
  payloadType: number
  mimeType: string
  clockRate: number
  channels?: number
}

export interface NativeRtpEncodingParameters {
  active?: boolean
  maxBitrate?: number
  maxFramerate?: number
  priority?: string
  rid?: string
  scaleResolutionDownBy?: number
  scalabilityMode?: string
  ssrc?: number
}

export interface NativeRtpHeaderExtensionCapability {
  uri: string
}

export interface NativeRtpHeaderExtensionParameters {
  uri: string
  id: number
  encrypted?: boolean
}

export interface NativeRtpParameters {
  transactionId: string
  codecs: Array<NativeRtpCodecParameters>
  headerExtensions: Array<NativeRtpHeaderExtensionParameters>
  encodings: Array<NativeRtpEncodingParameters>
  rtcp: NativeRtcpParameters
  degradationPreference?: string
}

export interface NativeSessionDescription {
  type: string
  sdp: string
}

export interface NativeVideoFrameEvent {
  data: Uint8Array
  width: number
  height: number
  timestampUs: bigint
  rotation: number
}

export interface NativeVideoSourceOptions {
  label?: string
  width: number
  height: number
  screencast?: boolean
}

export interface NativeVideoStreamOptions {
  queueSizeFrames?: number
}
