/**
 * Codegen: turns app.ts + the functions directory into
 * `_generated/{server.ts,api.ts,types.ts}`.
 *
 * Deterministic (same input -> byte-identical output, sorted everywhere) and
 * incremental (files are rewritten only when content changes, so watchers and
 * tsc see real edits only).
 *
 * Bootstrap order matters and is deliberate: `server.ts` depends only on the
 * manifest path, so it is written before anything imports user code — a fresh
 * project whose function modules import `_generated/server.ts` codegens in
 * one pass. Only `types.ts`/`api.ts` need the manifest loaded; function
 * modules are never imported by codegen at all.
 *
 * Generated files carry no runtime import of @ackerdb/server — clients bundle
 * only @ackerdb/core refs and a few variant constructors. (Type-only imports of
 * @ackerdb/server appear in types.ts/server.ts and compile away.)
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import {
  eventArgsTypeName,
  rowTypeName,
  type Schema,
  type EnumValidator,
  type UnionValidator,
  type Validator,
} from "@ackerdb/server";
import { EVENTS_NAMESPACE } from "@ackerdb/core";
import { importApp, listFunctionModules, listJobModules, type ModuleFile } from "./manifest.ts";
import type { AppConfig } from "./config.ts";

const HEADER = "/* eslint-disable */\n// Generated by `acker codegen`. Do not edit manually.\n";

function relImport(fromDir: string, toFile: string): string {
  const rel = relative(fromDir, toFile).split("\\").join("/");
  return rel.startsWith(".") ? rel : `./${rel}`;
}

function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;
  writeFileSync(path, content);
  return true;
}

interface JobsTypeTree {
  children: Map<string, JobsTypeTree>;
  alias?: string;
}

function renderJobsTree(node: JobsTypeTree, surface: string, indent: string): string {
  const lines: string[] = [];
  for (const [name, child] of [...node.children.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    if (child.alias !== undefined) {
      lines.push(`${indent}readonly ${name}: ${surface}<typeof ${child.alias}>;`);
    } else {
      lines.push(
        `${indent}readonly ${name}: {`,
        renderJobsTree(child, surface, `${indent}  `),
        `${indent}};`,
      );
    }
  }
  return lines.join("\n");
}

function serverTs(config: AppConfig, jobModules: ModuleFile[]): string {
  const appImport = relImport(config.generatedDir, config.appPath);
  const jobImports: string[] = [];
  const jobsRoot: JobsTypeTree = { children: new Map() };
  for (const module of jobModules) {
    const alias = `jm_${module.segments.join("_")}`;
    jobImports.push(
      `import type * as ${alias} from "${relImport(config.generatedDir, module.file)}";`,
    );
    let node = jobsRoot;
    for (const segment of module.segments) {
      let child = node.children.get(segment);
      if (child === undefined) node.children.set(segment, (child = { children: new Map() }));
      node = child;
    }
    node.alias = alias;
  }
  const jobsType = (name: string, surface: string): string =>
    jobsRoot.children.size === 0
      ? `type ${name} = Readonly<Record<never, never>>;`
      : `type ${name} = {\n${renderJobsTree(jobsRoot, surface, "  ")}\n};`;
  return `${HEADER}
import {
  mcp as mcpGeneric,
  channel as channelGeneric,
  httpHandler as httpHandlerGeneric,
  job as jobGeneric,
  realtime as realtimeGeneric,
  mcpAuth as mcpAuthGeneric,
  mutation as mutationGeneric,
  procedure as procedureGeneric,
  query as queryGeneric,
  service as serviceGeneric,
  sseProcedure as sseProcedureGeneric,
} from "@ackerdb/server";
import type {
  AppPluginCapabilities,
  AppSchema,
  ChannelBuilder,
  DbReader,
  DbWriter,
  HttpHandlerBuilder,
  HttpHandlerCtx as GenericHttpHandlerCtx,
  JobBuilder,
  JobCtx as GenericJobCtx,
  JobTxCtx as GenericJobTxCtx,
  McpAuthBuilder,
  McpBuilder,
  MutationBuilder,
  MutationCtx as GenericMutationCtx,
  MutationJobsOf,
  ProcedureBuilder,
  ProcedureCtx as GenericProcedureCtx,
  ProcedureJobsOf,
  QueryBuilder,
  QueryJobsOf,
  RealtimeBuilder,
  QueryCtx as GenericQueryCtx,
  ServiceBuilder,
  ServiceContext as GenericServiceContext,
  SseBuilder,
  SseCtx as GenericSseCtx,
  SystemCtx as GenericSystemCtx,
} from "@ackerdb/server";
import type app from "${appImport}";
${jobImports.join("\n")}${jobImports.length > 0 ? "\n" : ""}
export type Schema = AppSchema<typeof app>;
type QueryPlugins = AppPluginCapabilities<typeof app, "query">;
type MutationPlugins = AppPluginCapabilities<typeof app, "mutation">;
type ProcedurePlugins = AppPluginCapabilities<typeof app, "procedure">;
${jobsType("QueryJobs", "QueryJobsOf")}
${jobsType("MutationJobs", "MutationJobsOf")}
${jobsType("ProcedureJobs", "ProcedureJobsOf")}

export const query = queryGeneric as QueryBuilder<Schema, QueryPlugins, QueryJobs>;
export const channel = channelGeneric as ChannelBuilder<Schema>;
export const realtime = realtimeGeneric as unknown as RealtimeBuilder<Schema, ProcedurePlugins, MutationPlugins>;
export const mutation = mutationGeneric as MutationBuilder<Schema, MutationPlugins, MutationJobs>;
export const procedure = procedureGeneric as ProcedureBuilder<Schema, ProcedurePlugins, MutationPlugins, ProcedureJobs, MutationJobs>;
export const sseProcedure = sseProcedureGeneric as SseBuilder<Schema, ProcedurePlugins, MutationPlugins, ProcedureJobs, MutationJobs>;
export const httpHandler = httpHandlerGeneric as HttpHandlerBuilder<Schema, ProcedurePlugins, MutationPlugins>;
export const service = serviceGeneric as ServiceBuilder<Schema, ProcedurePlugins, MutationPlugins, ProcedureJobs, MutationJobs>;
export const job = jobGeneric as JobBuilder<Schema, ProcedurePlugins, MutationPlugins, ProcedureJobs, MutationJobs>;
export const mcp = mcpGeneric as McpBuilder<Schema>;
export const mcpAuth = mcpAuthGeneric as McpAuthBuilder<Schema>;

export type QueryCtx = GenericQueryCtx<Schema, QueryPlugins, QueryJobs>;
export type MutationCtx = GenericMutationCtx<Schema, MutationPlugins, MutationJobs>;
export type ProcedureCtx = GenericProcedureCtx<Schema, ProcedurePlugins, MutationPlugins, ProcedureJobs, MutationJobs>;
export type SseCtx = GenericSseCtx<Schema, ProcedurePlugins, MutationPlugins, ProcedureJobs, MutationJobs>;
export type HttpHandlerCtx = GenericHttpHandlerCtx<Schema, ProcedurePlugins, MutationPlugins>;
export type SystemCtx = GenericSystemCtx<Schema, ProcedurePlugins, MutationPlugins, ProcedureJobs, MutationJobs>;
export type ServiceCtx = GenericServiceContext<SystemCtx>;
export type JobCtx = GenericJobCtx<Schema, ProcedurePlugins, MutationPlugins, ProcedureJobs, MutationJobs>;
export type JobTxCtx = GenericJobTxCtx<Schema, MutationPlugins, MutationJobs>;
export type DatabaseReader = DbReader<Schema>;
export type DatabaseWriter = DbWriter<Schema>;
`;
}

interface ModuleTreeNode {
  children: Map<string, ModuleTreeNode>;
  alias?: string;
}

/**
 * Every name `api.ts` needs for itself carries the reserved `_`, which an API
 * path may never begin with. A group's name is written straight into
 * `export const <name>`, so reserving the prefix makes collision with a
 * generated import, the module type, or a module alias unrepresentable rather
 * than a list to keep in step. The two names left unprefixed — `api` and
 * `events` — are the surface, and the manifest refuses both.
 */
function apiTs(
  config: AppConfig,
  apiPaths: readonly string[],
  schema: Schema,
  modules: ModuleFile[],
): string {
  const imports: string[] = [];
  const root: ModuleTreeNode = { children: new Map() };
  for (const module of modules) {
    const alias = `_m_${module.segments.join("_")}`;
    imports.push(
      `import type * as ${alias} from "${relImport(config.generatedDir, module.file)}";`,
    );
    let node = root;
    for (const segment of module.segments) {
      let child = node.children.get(segment);
      if (child === undefined) node.children.set(segment, (child = { children: new Map() }));
      node = child;
    }
    node.alias = alias;
  }
  const renderTree = (node: ModuleTreeNode, indent: string): string => {
    const lines: string[] = [];
    for (const [name, child] of [...node.children.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      if (child.alias !== undefined) {
        lines.push(`${indent}${name}: typeof ${child.alias};`);
      } else {
        lines.push(`${indent}${name}: {`, renderTree(child, `${indent}  `), `${indent}};`);
      }
    }
    return lines.join("\n");
  };

  const eventTables = Object.keys(schema.tables)
    .filter((t) => schema.tables[t]!.kind === "event")
    .sort();
  const eventLines = eventTables.map(
    (t) =>
      `    ${t}: _EventRef<import("./types.ts").${eventArgsTypeName(t)}, import("./types.ts").${rowTypeName(t)}>;`,
  );

  // One binding per group the manifest declares, each a reference builder that
  // knows its own root. The addresses are identical — the socket names every
  // function by its dotted address — so only the type a binding selects and
  // the HTTP root its references resolve to differ.
  const groups = apiPaths.map(
    (path) =>
      `\n/** Functions declared \`apiPath: ${JSON.stringify(path)}\`: bound as \`${path}.*\`, served under \`/${path}/\`. */\n` +
      `export const ${path} = _apiGroup(${JSON.stringify(path)}) as unknown as _ApiFromModules<_Modules, ${JSON.stringify(path)}>;\n`,
  );

  return `${HEADER}
import { anyApi as _anyApi, apiGroup as _apiGroup } from "@ackerdb/core";
import type { ApiFromModules as _ApiFromModules, EventRef as _EventRef } from "@ackerdb/core";
${imports.join("\n")}${imports.length > 0 ? "\n" : ""}
type _Modules = {
${renderTree(root, "  ")}
};

export const api = _anyApi as unknown as _ApiFromModules<_Modules> & {
  ${EVENTS_NAMESPACE}: {
${eventLines.join("\n")}${eventLines.length > 0 ? "\n" : ""}  };
};

export const ${EVENTS_NAMESPACE} = api.${EVENTS_NAMESPACE};
${groups.join("")}`;
}

function typesTs(config: AppConfig, schema: Schema): string {
  const appImport = relImport(config.generatedDir, config.appPath);
  const parts: string[] = [];

  for (const name of [...schema.namedTypes.keys()].sort()) {
    const validator = schema.namedTypes.get(name)!;
    if (validator.kind === "enum") {
      const values = (validator as EnumValidator).values;
      parts.push(
        `export type ${name} = ${values.map((v) => JSON.stringify(v)).join(" | ")};`,
        `export const ${name} = {`,
        ...values.map((v) => `  ${v}: ${JSON.stringify(v)},`),
        `} as const;`,
        "",
      );
    } else {
      const members = (validator as UnionValidator).members;
      const variantType = (variant: string, member: Validator<unknown, string>) =>
        `{ tag: ${JSON.stringify(variant)}; value: ${member.tsType()} }`;
      parts.push(
        `export type ${name} =`,
        ...Object.entries(members).map(
          ([variant, member], i, all) =>
            `  | ${variantType(variant, member)}${i === all.length - 1 ? ";" : ""}`,
        ),
        `export const ${name} = {`,
        ...Object.entries(members).map(([variant, member]) =>
          member.kind === "tag"
            ? `  ${variant}: (): ${variantType(variant, member)} => ({ tag: ${JSON.stringify(variant)}, value: null }),`
            : `  ${variant}: (value: ${member.tsType()}): ${variantType(variant, member)} => ({ tag: ${JSON.stringify(variant)}, value }),`,
        ),
        `};`,
        "",
      );
    }
  }

  const rows = Object.keys(schema.tables)
    .sort()
    .map((table) => `export type ${rowTypeName(table)} = RowOf<Schema, ${JSON.stringify(table)}>;`);
  const eventArgs = Object.keys(schema.tables)
    .filter((table) => schema.tables[table]!.kind === "event")
    .sort()
    .map(
      (table) =>
        `export type ${eventArgsTypeName(table)} = EventArgsOf<Schema, ${JSON.stringify(table)}>;`,
    );

  return `${HEADER}
import type app from "${appImport}";
import type { AppSchema, EventArgsOf, FileGrantId, FileId, Identity, RowOf } from "@ackerdb/server";

type Schema = AppSchema<typeof app>;

export type { FileGrantId, FileId, Identity };

${parts.join("\n")}${parts.length > 0 ? "\n" : ""}${rows.join("\n")}${eventArgs.length > 0 ? "\n" : ""}${eventArgs.join("\n")}
`;
}

export interface CodegenResult {
  written: string[];
}

export async function runCodegen(config: AppConfig): Promise<CodegenResult> {
  mkdirSync(config.generatedDir, { recursive: true });
  const written: string[] = [];
  const emit = (name: string, content: string) => {
    if (writeIfChanged(join(config.generatedDir, name), content)) written.push(name);
  };

  // server.ts first: it needs only the manifest path and the jobs file list
  // (type-only imports), and writing it before importing user code is what
  // makes fresh projects codegen in one pass.
  emit("server.ts", serverTs(config, listJobModules(config)));

  const app = await importApp(config);
  const modules = listFunctionModules(config);
  emit("api.ts", apiTs(config, app.apiPaths, app.schema, modules));
  emit("types.ts", typesTs(config, app.schema));
  return { written };
}
