/**
 * Codegen: turns app.ts + the functions directory into
 * `_generated/{server.ts,api.ts,types.ts}`.
 *
 * Deterministic (same input -> byte-identical output, sorted everywhere) and
 * incremental (files are rewritten only when content changes, so watchers and
 * tsc see real edits only).
 *
 * Bootstrap order matters and is deliberate: `server.ts` depends only on the
 * manifest path, so it is written before anything imports user code — a fresh
 * project whose function modules import `_generated/server.ts` codegens in
 * one pass. Only `types.ts`/`api.ts` need the manifest loaded; function
 * modules are never imported by codegen at all.
 *
 * Generated files carry no runtime import of @ackerdb/server — clients bundle
 * only @ackerdb/core refs and a few variant constructors. (Type-only imports of
 * @ackerdb/server appear in types.ts/server.ts and compile away.)
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import {
  eventArgsTypeName,
  rowTypeName,
  type Schema,
  type EnumValidator,
  type UnionValidator,
  type Validator,
} from "@ackerdb/server";
import { EVENTS_NAMESPACE } from "@ackerdb/core";
import { importApp, listFunctionModules, listJobModules, type ModuleFile } from "./manifest.ts";
import type { AppConfig } from "./config.ts";

const HEADER = "/* eslint-disable */\n// Generated by `acker codegen`. Do not edit manually.\n";

function relImport(fromDir: string, toFile: string): string {
  const rel = relative(fromDir, toFile).split("\\").join("/");
  return rel.startsWith(".") ? rel : `./${rel}`;
}

function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;
  writeFileSync(path, content);
  return true;
}

interface ModuleTreeNode {
  children: Map<string, ModuleTreeNode>;
  alias?: string;
}

/**
 * The nested type tree for one module list, plus the type-only import each
 * module needs. Both generated trees are built this way, so a module file is
 * imported once and named once wherever it appears.
 */
function moduleTree(
  modules: readonly ModuleFile[],
  generatedDir: string,
  aliasPrefix: string,
): { imports: string[]; root: ModuleTreeNode } {
  const imports: string[] = [];
  const root: ModuleTreeNode = { children: new Map() };
  for (const module of modules) {
    const alias = `${aliasPrefix}${module.segments.join("_")}`;
    imports.push(`import type * as ${alias} from "${relImport(generatedDir, module.file)}";`);
    let node = root;
    for (const segment of module.segments) {
      let child = node.children.get(segment);
      if (child === undefined) node.children.set(segment, (child = { children: new Map() }));
      node = child;
    }
    node.alias = alias;
  }
  return { imports, root };
}

/**
 * Render one module tree as an object type. A node carries an alias when a
 * module file sits at its name, children when modules sit beneath it, and
 * *both* when a directory holds an `index.ts` next to its siblings — the
 * layout the collapse makes ordinary. The two are intersected rather than one
 * winning, because dropping either would leave a registered address with no
 * binding anybody can import.
 */
function renderModuleTree(
  node: ModuleTreeNode,
  leafType: (alias: string) => string,
  modifier: string,
  indent: string,
): string {
  const lines: string[] = [];
  for (const [name, child] of [...node.children.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const nested = child.children.size === 0
      ? undefined
      : `{\n${renderModuleTree(child, leafType, modifier, `${indent}  `)}\n${indent}}`;
    const leaf = child.alias === undefined ? undefined : leafType(child.alias);
    const type = leaf === undefined
      ? nested!
      : nested === undefined ? leaf : `${leaf} & ${nested}`;
    lines.push(`${indent}${modifier}${name}: ${type};`);
  }
  return lines.join("\n");
}

function serverTs(config: AppConfig, jobModules: ModuleFile[]): string {
  const appImport = relImport(config.generatedDir, config.appPath);
  const { imports: jobImports, root: jobsRoot } =
    moduleTree(jobModules, config.generatedDir, "jm_");
  const jobsType = (name: string, surface: string): string =>
    jobsRoot.children.size === 0
      ? `type ${name} = Readonly<Record<never, never>>;`
      : `type ${name} = {\n${
        renderModuleTree(jobsRoot, (alias) => `${surface}<typeof ${alias}>`, "readonly ", "  ")
      }\n};`;
  return `${HEADER}
import {
  channel as channelGeneric,
  httpHandler as httpHandlerGeneric,
  job as jobGeneric,
  mutation as mutationGeneric,
  procedure as procedureGeneric,
  query as queryGeneric,
  sseProcedure as sseProcedureGeneric,
} from "@ackerdb/server";
import type {
  AppSchema,
  AppScope,
  ChannelBuilder,
  DbReader,
  DbWriter,
  HttpHandlerBuilder,
  HttpHandlerCtx as GenericHttpHandlerCtx,
  JobBuilder,
  JobCtx as GenericJobCtx,
  JobTxCtx as GenericJobTxCtx,
  MutationBuilder,
  MutationCtx as GenericMutationCtx,
  MutationJobsOf,
  ProcedureBuilder,
  ProcedureCtx as GenericProcedureCtx,
  ProcedureJobsOf,
  QueryBuilder,
  QueryJobsOf,
  QueryCtx as GenericQueryCtx,
  SseBuilder,
  SseCtx as GenericSseCtx,
  SystemCtx as GenericSystemCtx,
} from "@ackerdb/server";
import type app from "${appImport}";
${jobImports.join("\n")}${jobImports.length > 0 ? "\n" : ""}
export type Schema = AppSchema<typeof app>;
/** The declared scope vocabulary; \`never\` when the application declares none. */
export type Scope = AppScope<typeof app>;
${jobsType("QueryJobs", "QueryJobsOf")}
${jobsType("MutationJobs", "MutationJobsOf")}
${jobsType("ProcedureJobs", "ProcedureJobsOf")}

export const query = queryGeneric as QueryBuilder<Schema, QueryJobs, Scope>;
export const channel = channelGeneric as ChannelBuilder<Schema>;
export const mutation = mutationGeneric as MutationBuilder<Schema, MutationJobs, Scope>;
export const procedure = procedureGeneric as ProcedureBuilder<Schema, ProcedureJobs, MutationJobs, Scope>;
export const sseProcedure = sseProcedureGeneric as SseBuilder<Schema, ProcedureJobs, MutationJobs, Scope>;
export const httpHandler = httpHandlerGeneric as HttpHandlerBuilder<Schema>;
export const job = jobGeneric as JobBuilder<Schema, ProcedureJobs, MutationJobs>;

export type QueryCtx = GenericQueryCtx<Schema, QueryJobs>;
export type MutationCtx = GenericMutationCtx<Schema, MutationJobs>;
export type ProcedureCtx = GenericProcedureCtx<Schema, ProcedureJobs, MutationJobs>;
export type SseCtx = GenericSseCtx<Schema, ProcedureJobs, MutationJobs>;
export type HttpHandlerCtx = GenericHttpHandlerCtx<Schema>;
export type SystemCtx = GenericSystemCtx<Schema, ProcedureJobs, MutationJobs>;
export type JobCtx = GenericJobCtx<Schema, ProcedureJobs, MutationJobs>;
export type JobTxCtx = GenericJobTxCtx<Schema, MutationJobs>;
export type DatabaseReader = DbReader<Schema>;
export type DatabaseWriter = DbWriter<Schema>;
`;
}

function apiTs(
  config: AppConfig,
  schema: Schema,
  modules: ModuleFile[],
): string {
  const { imports, root } = moduleTree(modules, config.generatedDir, "_m_");

  const eventTables = Object.keys(schema.tables)
    .filter((t) => schema.tables[t]!.kind === "event")
    .sort();
  const eventLines = eventTables.map(
    (t) =>
      `    ${t}: _EventRef<import("./types.ts").${eventArgsTypeName(t)}, import("./types.ts").${rowTypeName(t)}>;`,
  );

  return `${HEADER}
import { anyApi as _anyApi } from "@ackerdb/core";
import type { ApiFromModules as _ApiFromModules, EventRef as _EventRef } from "@ackerdb/core";
${imports.join("\n")}${imports.length > 0 ? "\n" : ""}
type _Modules = {
${renderModuleTree(root, (alias) => `typeof ${alias}`, "", "  ")}
};

export const api = _anyApi as unknown as _ApiFromModules<_Modules> & {
  ${EVENTS_NAMESPACE}: {
${eventLines.join("\n")}${eventLines.length > 0 ? "\n" : ""}  };
};

export const ${EVENTS_NAMESPACE} = api.${EVENTS_NAMESPACE};
`;
}

function typesTs(config: AppConfig, schema: Schema): string {
  const appImport = relImport(config.generatedDir, config.appPath);
  const parts: string[] = [];

  for (const name of [...schema.namedTypes.keys()].sort()) {
    const validator = schema.namedTypes.get(name)!;
    if (validator.kind === "enum") {
      const values = (validator as EnumValidator).values;
      parts.push(
        `export type ${name} = ${values.map((v) => JSON.stringify(v)).join(" | ")};`,
        `export const ${name} = {`,
        ...values.map((v) => `  ${v}: ${JSON.stringify(v)},`),
        `} as const;`,
        "",
      );
    } else {
      const members = (validator as UnionValidator).members;
      const variantType = (variant: string, member: Validator<unknown, string>) =>
        `{ tag: ${JSON.stringify(variant)}; value: ${member.tsType()} }`;
      parts.push(
        `export type ${name} =`,
        ...Object.entries(members).map(
          ([variant, member], i, all) =>
            `  | ${variantType(variant, member)}${i === all.length - 1 ? ";" : ""}`,
        ),
        `export const ${name} = {`,
        ...Object.entries(members).map(([variant, member]) =>
          member.kind === "tag"
            ? `  ${variant}: (): ${variantType(variant, member)} => ({ tag: ${JSON.stringify(variant)}, value: null }),`
            : `  ${variant}: (value: ${member.tsType()}): ${variantType(variant, member)} => ({ tag: ${JSON.stringify(variant)}, value }),`,
        ),
        `};`,
        "",
      );
    }
  }

  const rows = Object.keys(schema.tables)
    .sort()
    .map((table) => `export type ${rowTypeName(table)} = RowOf<Schema, ${JSON.stringify(table)}>;`);
  const eventArgs = Object.keys(schema.tables)
    .filter((table) => schema.tables[table]!.kind === "event")
    .sort()
    .map(
      (table) =>
        `export type ${eventArgsTypeName(table)} = EventArgsOf<Schema, ${JSON.stringify(table)}>;`,
    );

  return `${HEADER}
import type app from "${appImport}";
import type { AppSchema, EventArgsOf, FileGrantId, FileId, Identity, RowOf } from "@ackerdb/server";

type Schema = AppSchema<typeof app>;

export type { FileGrantId, FileId, Identity };

${parts.join("\n")}${parts.length > 0 ? "\n" : ""}${rows.join("\n")}${eventArgs.length > 0 ? "\n" : ""}${eventArgs.join("\n")}
`;
}

export interface CodegenResult {
  written: string[];
}

export async function runCodegen(config: AppConfig): Promise<CodegenResult> {
  mkdirSync(config.generatedDir, { recursive: true });
  const written: string[] = [];
  const emit = (name: string, content: string) => {
    if (writeIfChanged(join(config.generatedDir, name), content)) written.push(name);
  };

  // server.ts first: it needs only the manifest path and the jobs file list
  // (type-only imports), and writing it before importing user code is what
  // makes fresh projects codegen in one pass.
  emit("server.ts", serverTs(config, listJobModules(config)));

  const app = await importApp(config);
  const modules = listFunctionModules(config);
  emit("api.ts", apiTs(config, app.schema, modules));
  emit("types.ts", typesTs(config, app.schema));
  return { written };
}
