/* eslint-disable */
// Generated by `dbz codegen`. Do not edit manually.

import { anyApi } from "@dbzz/core";
import type { ApiFromModules, EventRef } from "@dbzz/core";
import type * as m_tasks from "../../../app/server/functions/tasks.ts";

export const api = anyApi as unknown as ApiFromModules<{
  tasks: typeof m_tasks;
}> & {
  events: {
  };
};

export const events = api.events;
