/* eslint-disable */
// Generated by `dbz codegen`. Do not edit manually.

import { anyApi } from "@dbzz/core";
import type { ApiFromModules, EventRef } from "@dbzz/core";
import type * as m_admin_mcp from "../../../app/server/functions/admin/mcp.ts";
import type * as m_admin_tokens from "../../../app/server/functions/admin/tokens.ts";
import type * as m_admin_tools_actions from "../../../app/server/functions/admin/tools/actions.ts";
import type * as m_admin_tools_guests from "../../../app/server/functions/admin/tools/guests.ts";
import type * as m_admin_tools_menuCategories from "../../../app/server/functions/admin/tools/menuCategories.ts";
import type * as m_admin_tools_menuItems from "../../../app/server/functions/admin/tools/menuItems.ts";
import type * as m_admin_tools_orderItems from "../../../app/server/functions/admin/tools/orderItems.ts";
import type * as m_admin_tools_orders from "../../../app/server/functions/admin/tools/orders.ts";
import type * as m_admin_tools_tables from "../../../app/server/functions/admin/tools/tables.ts";
import type * as m_auth from "../../../app/server/functions/auth.ts";
import type * as m_dashboard from "../../../app/server/functions/dashboard.ts";
import type * as m_kitchen from "../../../app/server/functions/kitchen.ts";
import type * as m_menu from "../../../app/server/functions/menu.ts";
import type * as m_orders from "../../../app/server/functions/orders.ts";
import type * as m_reminders from "../../../app/server/functions/reminders.ts";
import type * as m_setup from "../../../app/server/functions/setup.ts";
import type * as m_tables from "../../../app/server/functions/tables.ts";
import type * as m_users from "../../../app/server/functions/users.ts";

export const api = anyApi as unknown as ApiFromModules<{
  admin: {
    mcp: typeof m_admin_mcp;
    tokens: typeof m_admin_tokens;
    tools: {
      actions: typeof m_admin_tools_actions;
      guests: typeof m_admin_tools_guests;
      menuCategories: typeof m_admin_tools_menuCategories;
      menuItems: typeof m_admin_tools_menuItems;
      orderItems: typeof m_admin_tools_orderItems;
      orders: typeof m_admin_tools_orders;
      tables: typeof m_admin_tools_tables;
    };
  };
  auth: typeof m_auth;
  dashboard: typeof m_dashboard;
  kitchen: typeof m_kitchen;
  menu: typeof m_menu;
  orders: typeof m_orders;
  reminders: typeof m_reminders;
  setup: typeof m_setup;
  tables: typeof m_tables;
  users: typeof m_users;
}> & {
  events: {
    orderEvents: EventRef<import("./types.ts").OrderEventArgs, import("./types.ts").OrderEvent>;
    staffEvents: EventRef<import("./types.ts").StaffEventArgs, import("./types.ts").StaffEvent>;
  };
};

export const events = api.events;
