/* eslint-disable */
// Generated by `dbz codegen`. Do not edit manually.

import {
  createMcp as createMcpGeneric,
  mcpTool as mcpToolGeneric,
  mutation as mutationGeneric,
  procedure as procedureGeneric,
  query as queryGeneric,
  sseProcedure as sseProcedureGeneric,
} from "@dbzz/server";
import type {
  DbReader,
  DbWriter,
  McpBuilder,
  McpToolBuilder,
  McpToolCtx as GenericMcpToolCtx,
  MutationBuilder,
  MutationCtx as GenericMutationCtx,
  ProcedureBuilder,
  ProcedureCtx as GenericProcedureCtx,
  QueryBuilder,
  QueryCtx as GenericQueryCtx,
  SseBuilder,
  SseCtx as GenericSseCtx,
} from "@dbzz/server";
import type schema from "../../../app/server/schema.ts";

export type Schema = typeof schema;

export const query = queryGeneric as QueryBuilder<Schema>;
export const mutation = mutationGeneric as MutationBuilder<Schema>;
export const procedure = procedureGeneric as ProcedureBuilder<Schema>;
export const sseProcedure = sseProcedureGeneric as SseBuilder<Schema>;
export const createMcp = createMcpGeneric as McpBuilder<Schema>;
export const mcpTool = mcpToolGeneric as McpToolBuilder<Schema>;

export type QueryCtx = GenericQueryCtx<Schema>;
export type MutationCtx = GenericMutationCtx<Schema>;
export type ProcedureCtx = GenericProcedureCtx<Schema>;
export type SseCtx = GenericSseCtx<Schema>;
export type McpToolCtx = GenericMcpToolCtx<Schema>;
export type DatabaseReader = DbReader<Schema>;
export type DatabaseWriter = DbWriter<Schema>;
