/* eslint-disable */
// Generated by `dbzz codegen`. Do not edit manually.

import {
  createMcp as createMcpGeneric,
  mcpTool as mcpToolGeneric,
  mutation as mutationGeneric,
  procedure as procedureGeneric,
  query as queryGeneric,
  sseProcedure as sseProcedureGeneric,
} from "@dbzz/server";
import type {
  AppPluginCapabilities,
  AppSchema,
  DbReader,
  DbWriter,
  McpBuilder,
  McpToolBuilder,
  McpToolCtx as GenericMcpToolCtx,
  MutationBuilder,
  MutationCtx as GenericMutationCtx,
  ProcedureBuilder,
  ProcedureCtx as GenericProcedureCtx,
  QueryBuilder,
  QueryCtx as GenericQueryCtx,
  SseBuilder,
  SseCtx as GenericSseCtx,
} from "@dbzz/server";
import type app from "../../../app/server/app.ts";

export type Schema = AppSchema<typeof app>;
type QueryPlugins = AppPluginCapabilities<typeof app, "query">;
type MutationPlugins = AppPluginCapabilities<typeof app, "mutation">;
type ProcedurePlugins = AppPluginCapabilities<typeof app, "procedure">;

export const query = queryGeneric as QueryBuilder<Schema, QueryPlugins>;
export const mutation = mutationGeneric as MutationBuilder<Schema, MutationPlugins>;
export const procedure = procedureGeneric as ProcedureBuilder<Schema, ProcedurePlugins, MutationPlugins>;
export const sseProcedure = sseProcedureGeneric as SseBuilder<Schema, ProcedurePlugins, MutationPlugins>;
export const createMcp = createMcpGeneric as McpBuilder<Schema>;
export const mcpTool = mcpToolGeneric as McpToolBuilder<Schema>;

export type QueryCtx = GenericQueryCtx<Schema, QueryPlugins>;
export type MutationCtx = GenericMutationCtx<Schema, MutationPlugins>;
export type ProcedureCtx = GenericProcedureCtx<Schema, ProcedurePlugins, MutationPlugins>;
export type SseCtx = GenericSseCtx<Schema, ProcedurePlugins, MutationPlugins>;
export type McpToolCtx = GenericMcpToolCtx<Schema>;
export type DatabaseReader = DbReader<Schema>;
export type DatabaseWriter = DbWriter<Schema>;
