/* eslint-disable */
// Generated by `dbz codegen`. Do not edit manually.

import type schema from "../../../app/server/schema.ts";
import type { EventArgsOf, Identity, RowOf } from "@dbzz/server";

export type { Identity };

export type Task = RowOf<typeof schema, "tasks">;
