/* eslint-disable */
// Generated by `dbzz codegen`. Do not edit manually.

import type app from "../../../app/server/app.ts";
import type { AppSchema, EventArgsOf, Identity, RowOf } from "@dbzz/server";

type Schema = AppSchema<typeof app>;

export type { Identity };

export type ItemStatus = "ORDERED" | "PREPARING" | "PREPARED" | "SERVED" | "CANCELLED";
export const ItemStatus = {
  ORDERED: "ORDERED",
  PREPARING: "PREPARING",
  PREPARED: "PREPARED",
  SERVED: "SERVED",
  CANCELLED: "CANCELLED",
} as const;

export type OrderEventKind = "ITEM_STATUS" | "ORDER_STATUS";
export const OrderEventKind = {
  ITEM_STATUS: "ITEM_STATUS",
  ORDER_STATUS: "ORDER_STATUS",
} as const;

export type OrderStatus = "OPEN" | "PAID" | "CANCELLED";
export const OrderStatus = {
  OPEN: "OPEN",
  PAID: "PAID",
  CANCELLED: "CANCELLED",
} as const;

export type StaffEventKind = "KITCHEN_REMINDER";
export const StaffEventKind = {
  KITCHEN_REMINDER: "KITCHEN_REMINDER",
} as const;

export type KitchenReminder = RowOf<Schema, "kitchenReminders">;
export type MenuCategory = RowOf<Schema, "menuCategories">;
export type MenuItem = RowOf<Schema, "menuItems">;
export type OrderEvent = RowOf<Schema, "orderEvents">;
export type OrderItem = RowOf<Schema, "orderItems">;
export type Order = RowOf<Schema, "orders">;
export type RestaurantTable = RowOf<Schema, "restaurantTables">;
export type SetupState = RowOf<Schema, "setupState">;
export type StaffEvent = RowOf<Schema, "staffEvents">;
export type User = RowOf<Schema, "users">;
export type OrderEventArgs = EventArgsOf<Schema, "orderEvents">;
export type StaffEventArgs = EventArgsOf<Schema, "staffEvents">;
