/* eslint-disable */
// Generated by `dbzz generate`. Do not edit manually.

import { defineMigration as defineMigrationRuntime } from "@dbzz/server";
import type { Renames } from "@dbzz/server";

/** Rows as they existed BEFORE this migration (the recorded pre-snapshot). */
type KitchenRemindersBefore = { id: bigint; orderItemId: bigint; expectedStatus: "ORDERED" | "PREPARING" | "PREPARED" | "SERVED" | "CANCELLED"; at: number };
type MenuCategoriesBefore = { id: bigint; name: string; slug: string; sortOrder: number; active: boolean; createdAt: number; updatedAt: number };
type MenuItemsBefore = { id: bigint; categoryId: bigint; name: string; description: string; image: string; priceCents: number; sortOrder: number; active: boolean; createdAt: number; updatedAt: number };
type OrderItemsBefore = { id: bigint; orderId: bigint; menuItemId: bigint; name: string; image: string; unitPriceCents: number; quantity: number; note: string | null; status: "ORDERED" | "PREPARING" | "PREPARED" | "SERVED" | "CANCELLED"; orderedAt: number; statusChangedAt: number };
type OrdersBefore = { id: bigint; userId: bigint; tableId: bigint; openUserId: bigint | null; openTableId: bigint | null; status: "OPEN" | "PAID" | "CANCELLED"; totalCents: number; openedAt: number; closedAt: number | null };
type RestaurantTablesBefore = { id: bigint; number: number; seats: number; active: boolean; createdAt: number; updatedAt: number };
type SetupStateBefore = { id: bigint; key: string; completedAt: number };
type UsersBefore = { id: bigint; identity: bigint | null; email: string; name: string; createdAt: number; updatedAt: number };

/** Rows of the NEW schema this migration targets. */
export type KitchenRemindersRow = { id: bigint; orderItemId: bigint; expectedStatus: "ORDERED" | "PREPARING" | "PREPARED" | "SERVED" | "CANCELLED"; at: number };
export type MenuCategoriesRow = { id: bigint; name: string; sortOrder: number; active: boolean; createdAt: number; updatedAt: number };
export type MenuItemsRow = { id: bigint; categoryId: bigint; name: string; description: string; image: string; priceCents: number; sortOrder: number; active: boolean; createdAt: number; updatedAt: number };
export type OrderItemsRow = { id: bigint; orderId: bigint; menuItemId: bigint; name: string; image: string; unitPriceCents: number; quantity: number; note: string | null; status: "ORDERED" | "PREPARING" | "PREPARED" | "SERVED" | "CANCELLED"; orderedAt: number; statusChangedAt: number };
export type OrdersRow = { id: bigint; userId: bigint; tableId: bigint; openUserId: bigint | null; openTableId: bigint | null; status: "OPEN" | "PAID" | "CANCELLED"; totalCents: number; openedAt: number; closedAt: number | null };
export type RestaurantTablesRow = { id: bigint; number: number; seats: number; active: boolean; createdAt: number; updatedAt: number };
export type SetupStateRow = { id: bigint; key: string; completedAt: number };
export type UsersRow = { id: bigint; identity: bigint | null; email: string; name: string; createdAt: number; updatedAt: number };

/** Insert shapes for the NEW schema (primary key omitted, nullable columns optional). */
type KitchenRemindersInsert = { orderItemId: bigint; expectedStatus: "ORDERED" | "PREPARING" | "PREPARED" | "SERVED" | "CANCELLED"; at: number };
type MenuCategoriesInsert = { name: string; sortOrder: number; active: boolean; createdAt: number; updatedAt: number };
type MenuItemsInsert = { categoryId: bigint; name: string; description: string; image: string; priceCents: number; sortOrder: number; active: boolean; createdAt: number; updatedAt: number };
type OrderItemsInsert = { orderId: bigint; menuItemId: bigint; name: string; image: string; unitPriceCents: number; quantity: number; note?: string | null; status: "ORDERED" | "PREPARING" | "PREPARED" | "SERVED" | "CANCELLED"; orderedAt: number; statusChangedAt: number };
type OrdersInsert = { userId: bigint; tableId: bigint; openUserId?: bigint | null; openTableId?: bigint | null; status: "OPEN" | "PAID" | "CANCELLED"; totalCents: number; openedAt: number; closedAt?: number | null };
type RestaurantTablesInsert = { number: number; seats: number; active: boolean; createdAt: number; updatedAt: number };
type SetupStateInsert = { key: string; completedAt: number };
type UsersInsert = { identity?: bigint | null; email: string; name: string; createdAt: number; updatedAt: number };

interface MigrationBeforeTable<Row> {
  get(id: bigint): Promise<Row | null>;
  scan(): AsyncIterableIterator<Row>;
}

interface MigrationInserts {
  kitchenReminders: KitchenRemindersInsert;
  menuCategories: MenuCategoriesInsert;
  menuItems: MenuItemsInsert;
  orderItems: OrderItemsInsert;
  orders: OrdersInsert;
  restaurantTables: RestaurantTablesInsert;
  setupState: SetupStateInsert;
  users: UsersInsert;
}

interface MigrationContext {
  readonly before: {
    kitchenReminders: MigrationBeforeTable<KitchenRemindersBefore>;
    menuCategories: MigrationBeforeTable<MenuCategoriesBefore>;
    menuItems: MigrationBeforeTable<MenuItemsBefore>;
    orderItems: MigrationBeforeTable<OrderItemsBefore>;
    orders: MigrationBeforeTable<OrdersBefore>;
    restaurantTables: MigrationBeforeTable<RestaurantTablesBefore>;
    setupState: MigrationBeforeTable<SetupStateBefore>;
    users: MigrationBeforeTable<UsersBefore>;
  };
  insert<Table extends keyof MigrationInserts>(table: Table, row: MigrationInserts[Table]): void;
}

interface MigrationDefinition {
  renames?: Renames;
  tables?: {
    kitchenReminders?: (row: KitchenRemindersBefore, ctx: MigrationContext) => KitchenRemindersRow | null | Promise<KitchenRemindersRow | null>;
    menuCategories?: (row: MenuCategoriesBefore, ctx: MigrationContext) => MenuCategoriesRow | null | Promise<MenuCategoriesRow | null>;
    menuItems?: (row: MenuItemsBefore, ctx: MigrationContext) => MenuItemsRow | null | Promise<MenuItemsRow | null>;
    orderItems?: (row: OrderItemsBefore, ctx: MigrationContext) => OrderItemsRow | null | Promise<OrderItemsRow | null>;
    orders?: (row: OrdersBefore, ctx: MigrationContext) => OrdersRow | null | Promise<OrdersRow | null>;
    restaurantTables?: (row: RestaurantTablesBefore, ctx: MigrationContext) => RestaurantTablesRow | null | Promise<RestaurantTablesRow | null>;
    setupState?: (row: SetupStateBefore, ctx: MigrationContext) => SetupStateRow | null | Promise<SetupStateRow | null>;
    users?: (row: UsersBefore, ctx: MigrationContext) => UsersRow | null | Promise<UsersRow | null>;
  };
}

/** The runtime `defineMigration`, typed for exactly this migration step. */
export const defineMigration = defineMigrationRuntime as unknown as (
  migration: MigrationDefinition,
) => MigrationDefinition;
