/**
 * Codegen: turns schema.ts + the functions directory into
 * `_generated/{server.ts,api.ts,types.ts}`.
 *
 * Deterministic (same input -> byte-identical output, sorted everywhere) and
 * incremental (files are rewritten only when content changes, so watchers and
 * tsc see real edits only).
 *
 * Bootstrap order matters and is deliberate: `server.ts` depends only on the
 * schema *path*, so it is written before anything imports user code — a fresh
 * project whose function modules import `_generated/server.ts` codegens in
 * one pass. Only `types.ts`/`api.ts` need the schema module loaded; function
 * modules are never imported by codegen at all.
 *
 * Generated files carry no runtime import of @dbzz/server — clients bundle
 * only @dbzz/core refs and a few variant constructors. (Type-only imports of
 * @dbzz/server appear in types.ts/server.ts and compile away.)
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import {
  eventArgsTypeName,
  rowTypeName,
  Schema,
  type EnumValidator,
  type UnionValidator,
  type Validator,
} from "@dbzz/server";
import { importSchema, listFunctionModules, type FunctionModuleFile } from "./app.ts";
import type { AppConfig } from "./config.ts";

const HEADER = "/* eslint-disable */\n// Generated by `dbz codegen`. Do not edit manually.\n";

function relImport(fromDir: string, toFile: string): string {
  const rel = relative(fromDir, toFile).split("\\").join("/");
  return rel.startsWith(".") ? rel : `./${rel}`;
}

function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;
  writeFileSync(path, content);
  return true;
}

function serverTs(config: AppConfig): string {
  const schemaImport = relImport(config.generatedDir, config.schemaPath);
  return `${HEADER}
import {
  createMcp as createMcpGeneric,
  mutation as mutationGeneric,
  procedure as procedureGeneric,
  query as queryGeneric,
  sseProcedure as sseProcedureGeneric,
} from "@dbzz/server";
import type {
  DbReader,
  DbWriter,
  McpBuilder,
  McpToolCtx as GenericMcpToolCtx,
  MutationBuilder,
  MutationCtx as GenericMutationCtx,
  ProcedureBuilder,
  ProcedureCtx as GenericProcedureCtx,
  QueryBuilder,
  QueryCtx as GenericQueryCtx,
  SseBuilder,
  SseCtx as GenericSseCtx,
} from "@dbzz/server";
import type schema from "${schemaImport}";

export type Schema = typeof schema;

export const query = queryGeneric as QueryBuilder<Schema>;
export const mutation = mutationGeneric as MutationBuilder<Schema>;
export const procedure = procedureGeneric as ProcedureBuilder<Schema>;
export const sseProcedure = sseProcedureGeneric as SseBuilder<Schema>;
export const createMcp = createMcpGeneric as McpBuilder<Schema>;

export type QueryCtx = GenericQueryCtx<Schema>;
export type MutationCtx = GenericMutationCtx<Schema>;
export type ProcedureCtx = GenericProcedureCtx<Schema>;
export type SseCtx = GenericSseCtx<Schema>;
export type McpToolCtx = GenericMcpToolCtx<Schema>;
export type DatabaseReader = DbReader<Schema>;
export type DatabaseWriter = DbWriter<Schema>;
`;
}

interface ModuleTreeNode {
  children: Map<string, ModuleTreeNode>;
  alias?: string;
}

function apiTs(config: AppConfig, schema: Schema, modules: FunctionModuleFile[]): string {
  const imports: string[] = [];
  const root: ModuleTreeNode = { children: new Map() };
  for (const module of modules) {
    const alias = `m_${module.segments.join("_")}`;
    imports.push(
      `import type * as ${alias} from "${relImport(config.generatedDir, module.file)}";`,
    );
    let node = root;
    for (const segment of module.segments) {
      let child = node.children.get(segment);
      if (child === undefined) node.children.set(segment, (child = { children: new Map() }));
      node = child;
    }
    node.alias = alias;
  }
  const renderTree = (node: ModuleTreeNode, indent: string): string => {
    const lines: string[] = [];
    for (const [name, child] of [...node.children.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      if (child.alias !== undefined) {
        lines.push(`${indent}${name}: typeof ${child.alias};`);
      } else {
        lines.push(`${indent}${name}: {`, renderTree(child, `${indent}  `), `${indent}};`);
      }
    }
    return lines.join("\n");
  };

  const eventTables = Object.keys(schema.tables)
    .filter((t) => schema.tables[t]!.kind === "event")
    .sort();
  const eventLines = eventTables.map(
    (t) =>
      `    ${t}: EventRef<import("./types.ts").${eventArgsTypeName(t)}, import("./types.ts").${rowTypeName(t)}>;`,
  );

  return `${HEADER}
import { anyApi } from "@dbzz/core";
import type { ApiFromModules, EventRef } from "@dbzz/core";
${imports.join("\n")}${imports.length > 0 ? "\n" : ""}
export const api = anyApi as unknown as ApiFromModules<{
${renderTree(root, "  ")}
}> & {
  events: {
${eventLines.join("\n")}${eventLines.length > 0 ? "\n" : ""}  };
};

export const events = api.events;
`;
}

function typesTs(config: AppConfig, schema: Schema): string {
  const schemaImport = relImport(config.generatedDir, config.schemaPath);
  const parts: string[] = [];

  for (const name of [...schema.namedTypes.keys()].sort()) {
    const validator = schema.namedTypes.get(name)!;
    if (validator.kind === "enum") {
      const values = (validator as EnumValidator).values;
      parts.push(
        `export type ${name} = ${values.map((v) => JSON.stringify(v)).join(" | ")};`,
        `export const ${name} = {`,
        ...values.map((v) => `  ${v}: ${JSON.stringify(v)},`),
        `} as const;`,
        "",
      );
    } else {
      const members = (validator as UnionValidator).members;
      const variantType = (variant: string, member: Validator<unknown, string>) =>
        `{ tag: ${JSON.stringify(variant)}; value: ${member.tsType()} }`;
      parts.push(
        `export type ${name} =`,
        ...Object.entries(members).map(
          ([variant, member], i, all) =>
            `  | ${variantType(variant, member)}${i === all.length - 1 ? ";" : ""}`,
        ),
        `export const ${name} = {`,
        ...Object.entries(members).map(([variant, member]) =>
          member.kind === "tag"
            ? `  ${variant}: (): ${variantType(variant, member)} => ({ tag: ${JSON.stringify(variant)}, value: null }),`
            : `  ${variant}: (value: ${member.tsType()}): ${variantType(variant, member)} => ({ tag: ${JSON.stringify(variant)}, value }),`,
        ),
        `};`,
        "",
      );
    }
  }

  const rows = Object.keys(schema.tables)
    .sort()
    .map((table) => `export type ${rowTypeName(table)} = RowOf<typeof schema, ${JSON.stringify(table)}>;`);
  const eventArgs = Object.keys(schema.tables)
    .filter((table) => schema.tables[table]!.kind === "event")
    .sort()
    .map(
      (table) =>
        `export type ${eventArgsTypeName(table)} = EventArgsOf<typeof schema, ${JSON.stringify(table)}>;`,
    );

  return `${HEADER}
import type schema from "${schemaImport}";
import type { EventArgsOf, Identity, RowOf } from "@dbzz/server";

export type { Identity };

${parts.join("\n")}${parts.length > 0 ? "\n" : ""}${rows.join("\n")}${eventArgs.length > 0 ? "\n" : ""}${eventArgs.join("\n")}
`;
}

export interface CodegenResult {
  written: string[];
}

export async function runCodegen(config: AppConfig): Promise<CodegenResult> {
  mkdirSync(config.generatedDir, { recursive: true });
  const written: string[] = [];
  const emit = (name: string, content: string) => {
    if (writeIfChanged(join(config.generatedDir, name), content)) written.push(name);
  };

  // server.ts first: it only needs the schema *path*, and writing it before
  // importing user code is what makes fresh projects codegen in one pass.
  emit("server.ts", serverTs(config));

  const schema = await importSchema(config);
  const modules = listFunctionModules(config);
  emit("api.ts", apiTs(config, schema, modules));
  emit("types.ts", typesTs(config, schema));
  return { written };
}
