// Migration generated by `dbz generate`. Complete each TODO below, then this file is yours to edit.
import { defineMigration, type MenuCategoriesRow } from "./meta/0001_add_category_slug.types.ts";

export default defineMigration({
  tables: {
    menuCategories: (row): MenuCategoriesRow => ({
      ...row,
      slug: row.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
    }),
  },
});
