// Migration generated by `acker generate`. Complete each TODO below, then this file is yours to edit.
import { defineMigration } from "./meta/0002_drop_category_slug.types.ts";

export default defineMigration({
  tables: {
    menuCategories: ({ slug, ...rest }) => rest,
  },
});
