/**
 * Migration generation: a pure function turning `(stored snapshot, live schema,
 * rename answers)` into the three on-disk artifacts of one migration step. No
 * TTY, no filesystem — the interactive form and the CLI command that drives them
 * live in the command layer; this module only computes strings.
 *
 * The verdict comes from the same seams reconcile uses: classify the diff of the
 * renamed-stored snapshot against the target, then let each refusal drive a stub:
 *   - a dropped table becomes a `null` acknowledgment,
 *   - a table refused only by column drops becomes a complete destructuring
 *     transform that names every dropped field (so it compiles as generated),
 *   - anything else becomes a typed hole — an arrow with the NEW row type
 *     annotated and a body of `// TODO(...)` lines, one per refusal, which does
 *     NOT compile until the developer answers it.
 *
 * Three artifacts:
 *   - `NNNN_name.ts`             the scaffold, importing only its types companion;
 *   - `meta/NNNN_name.types.ts`  generated TypeScript that types the scaffold with
 *                                zero wiring (old/new row types, insert shapes, a
 *                                specialized `defineMigration`);
 *   - `meta/NNNN_name.json`      exactly the loader's `{number,name,fingerprint,pre,target}`.
 *
 * Type rendering is STRUCTURAL: old and new type names can collide across the two
 * worlds, so nothing is emitted by name — enums render as unions of string
 * literals, unions as `{ tag; value }` unions, everything else recursively. Same
 * inputs yield byte-identical artifacts (tables sorted, columns in snapshot
 * order, refusal comments in classification order).
 */
import { decode } from "@dbzz/core";
import {
  applyRenames,
  classifySchemaDiff,
  diffSnapshots,
  migrationFingerprint,
  refusalSite,
  snapshotOf,
  stepLabel,
  type Descriptor,
  type Renames,
  type Schema,
  type SchemaRefusal,
  type SchemaSnapshot,
  type TableSnapshot,
} from "@dbzz/server";

/** Raised when a descriptor kind cannot be rendered structurally — a hard stop. */
export class GenerateError extends Error {}

export interface GenerateMigrationInput {
  /** 1-based, strictly increasing across the chain (derived by the command). */
  number: number;
  /** The identifier half of `NNNN_name` (derived by the command). */
  name: string;
  /** The snapshot the database last stored — types the before-state, recorded as `pre`. */
  pre: SchemaSnapshot;
  /** The live declared schema; its snapshot becomes the `target` contract. */
  schema: Schema;
  /** The rename answers, keyed exactly as the runtime expects; omit when there are none. */
  renames?: Renames;
  /**
   * Refusals the pure diff cannot see: the database-probed `unique-index-duplicates`
   * from the plan. Merged into the shape-classified refusals so the offending
   * table gets a volunteered dedupe transform stub.
   */
  probedRefusals?: SchemaRefusal[];
}

export interface GeneratedMigration {
  /** `NNNN_name.ts` — the scaffold to complete, then edit freely. */
  migrationTs: string;
  /** `meta/NNNN_name.types.ts` — generated, never hand-edited. */
  typesTs: string;
  /** `meta/NNNN_name.json` — the loader's sidecar contract. */
  metaJson: string;
}

const TYPES_HEADER = "/* eslint-disable */\n// Generated by `dbz generate`. Do not edit manually.\n";
const SCAFFOLD_HEADER =
  "// Migration generated by `dbz generate`. Complete each TODO below, then this file is yours to edit.\n";

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
/** Object keys that are valid identifiers stay bare; the rest are quoted. */
function identKey(name: string): string {
  return IDENT.test(name) ? name : JSON.stringify(name);
}

function cap(name: string): string {
  return name.length === 0 ? name : name.charAt(0).toUpperCase() + name.slice(1);
}

const beforeName = (table: string): string => `${cap(table)}Before`;
const rowName = (table: string): string => `${cap(table)}Row`;
const insertName = (table: string): string => `${cap(table)}Insert`;

const byName = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

// -- structural type rendering ------------------------------------------------

/** Parenthesize a type before embedding it in `T[]` (or any postfix position). */
function paren(ts: string): string {
  return /[|&]/.test(ts) ? `(${ts})` : ts;
}

/** Reproduce v.literal's TypeScript text from the descriptor's stored value. */
function literalTs(value: unknown): string {
  if (typeof value === "bigint") return `${value}n`;
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

/**
 * The render facet of the descriptor seam, co-located CLI-side because it emits
 * TypeScript text (a codegen concern that also owns `GenerateError`): a table
 * keyed by the same descriptor kinds the server seam uses, mapping each to its
 * structural type text. bigint/identity/pk as bigint, int/float/scheduleAt as
 * number, bytes as Uint8Array, jsonb as the codegen convention (`unknown`), enums as
 * string-literal unions, unions as discriminated `{ tag; value }` unions,
 * objects/arrays/nullables recursively.
 */
const RENDER_KIND: Record<string, (desc: Descriptor) => string> = {
  pk: () => "bigint",
  bigint: () => "bigint",
  identity: () => "bigint",
  string: () => "string",
  int: () => "number",
  float: () => "number",
  scheduleAt: () => "number",
  boolean: () => "boolean",
  bytes: () => "Uint8Array",
  jsonb: () => "unknown",
  tag: () => "null",
  literal: (desc) => literalTs(decode(JSON.stringify(desc["v"]))),
  enum: (desc) => (desc["values"] as string[]).map((v) => JSON.stringify(v)).join(" | "),
  nullable: (desc) => `${renderType(desc["inner"] as Descriptor)} | null`,
  array: (desc) => `${paren(renderType(desc["el"] as Descriptor))}[]`,
  object: (desc) => renderShape(desc["shape"] as Record<string, Descriptor>),
  union: (desc) =>
    Object.entries(desc["members"] as Record<string, Descriptor>)
      .map(([tag, member]) => `{ tag: ${JSON.stringify(tag)}; value: ${renderType(member)} }`)
      .join(" | "),
};

function renderType(desc: Descriptor): string {
  const render = RENDER_KIND[desc["k"]];
  if (render === undefined) throw new GenerateError(`cannot render descriptor kind "${String(desc["k"])}" structurally`);
  return render(desc);
}

function renderShape(shape: Record<string, Descriptor>): string {
  const fields = Object.entries(shape).map(([key, desc]) => `${identKey(key)}: ${renderType(desc)}`);
  return fields.length === 0 ? "Record<string, never>" : `{ ${fields.join("; ")} }`;
}

/** A whole row: every column in snapshot order, the primary key rendered as bigint. */
function renderRow(table: TableSnapshot): string {
  return renderShape(table.columns);
}

/** The insert shape: primary key omitted, nullable columns optional. */
function renderInsert(table: TableSnapshot): string {
  const fields: string[] = [];
  for (const [col, desc] of Object.entries(table.columns)) {
    if (desc["k"] === "pk") continue;
    const optional = desc["k"] === "nullable";
    fields.push(`${identKey(col)}${optional ? "?" : ""}: ${renderType(desc)}`);
  }
  return fields.length === 0 ? "Record<string, never>" : `{ ${fields.join("; ")} }`;
}

// -- rename answer rendering --------------------------------------------------

/** Render a rename answer as a TypeScript object literal, keys sorted for determinism. */
function tsLiteral(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(value);
  if (value !== null && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const entries = Object.keys(record)
      .sort(byName)
      .map((key) => `${identKey(key)}: ${tsLiteral(record[key])}`);
    return `{ ${entries.join(", ")} }`;
  }
  return JSON.stringify(value);
}

/** The `renames` literal, or `null` when every section is empty. */
function renderRenames(renames: Renames): string | null {
  const clean: Record<string, unknown> = {};
  for (const key of ["tables", "columns", "variants"] as const) {
    const section = renames[key];
    if (section !== undefined && Object.keys(section).length > 0) clean[key] = section;
  }
  return Object.keys(clean).length === 0 ? null : tsLiteral(clean);
}

// -- the pure function --------------------------------------------------------

interface RealTables {
  pre: string[];
  target: string[];
}

/** The two worlds' real (non-event) table names, each sorted. */
function realTables(pre: SchemaSnapshot, target: SchemaSnapshot): RealTables {
  const of = (snap: SchemaSnapshot): string[] =>
    Object.keys(snap.tables)
      .filter((t) => snap.tables[t]!.kind === "table")
      .sort(byName);
  return { pre: of(pre), target: of(target) };
}

export function generateMigration(input: GenerateMigrationInput): GeneratedMigration {
  const { number, name, pre } = input;
  const renames = input.renames ?? {};
  const normalizedRenames = {
    tables: renames.tables ?? {},
    columns: renames.columns ?? {},
    variants: renames.variants ?? {},
  };
  const target = snapshotOf(input.schema);

  const diff = diffSnapshots(applyRenames(pre, normalizedRenames), target);
  const { refusals } = classifySchemaDiff(diff);
  const allRefusals = [...refusals, ...(input.probedRefusals ?? [])];

  const stem = stepLabel({ number, name });
  return {
    migrationTs: renderScaffold(stem, renames, allRefusals),
    typesTs: renderTypes(pre, target, normalizedRenames),
    metaJson: `${JSON.stringify({ number, name, fingerprint: migrationFingerprint(target), pre, target }, null, 2)}\n`,
  };
}

// -- the scaffold -------------------------------------------------------------

/** Group refusals by table, preserving classification order within each group. */
function groupRefusals(refusals: SchemaRefusal[]): Map<string, SchemaRefusal[]> {
  const byTable = new Map<string, SchemaRefusal[]>();
  for (const refusal of refusals) {
    let group = byTable.get(refusal.table);
    if (group === undefined) byTable.set(refusal.table, (group = []));
    group.push(refusal);
  }
  return byTable;
}

/** The TODO body for one refusal — the dedupe hole spells out its survivor/drop contract. */
function todoText(refusal: SchemaRefusal): string {
  return refusal.reason === "unique-index-duplicates"
    ? `${refusal.question} — return the surviving row, or null to drop this one`
    : refusal.question;
}

function renderScaffold(stem: string, renames: Renames, refusals: SchemaRefusal[]): string {
  const holeTables = new Set<string>();
  const entries: { key: string; text: string }[] = [];

  for (const [table, group] of groupRefusals(refusals)) {
    const drop = group.find((r) => r.reason === "table-dropped" || r.reason === "table-to-event");
    if (drop !== undefined) {
      // A dropped table: acknowledge with `null`; the developer may hand-replace
      // it with a salvage transform (the specialized type admits that too).
      entries.push({ key: table, text: `    ${identKey(table)}: null, // ${drop.question}` });
      continue;
    }
    const renamedColumns = renames.columns?.[table];
    const columnRenamed = renamedColumns !== undefined && Object.keys(renamedColumns).length > 0;
    if (!columnRenamed && group.every((r) => r.reason === "column-dropped")) {
      // Column drops only, no column rename in play: a complete destructuring
      // transform whose visible bindings ARE the acknowledgment of each drop.
      const binding = group.map((r) => r.column!).join(", ");
      entries.push({ key: table, text: `    ${identKey(table)}: ({ ${binding}, ...rest }) => rest,` });
      continue;
    }
    // Everything else — a typed hole: annotated with the NEW row type, its body
    // only TODO lines. A declared return type with no return does not compile.
    // The probed unique-index refusal is volunteered here: same shape old/new, so
    // the hole is the forcing function and the physical unique index at apply is
    // the final enforcer (a non-deduping transform fails cleanly and rolls back).
    holeTables.add(table);
    const todos = group.map((r) => `      // TODO(${refusalSite(r)}): ${todoText(r)}`).join("\n");
    entries.push({
      key: table,
      text: `    ${identKey(table)}: (row): ${rowName(table)} => {\n${todos}\n    },`,
    });
  }

  entries.sort((a, b) => byName(a.key, b.key));

  const parts: string[] = [];
  const renamesLiteral = renderRenames(renames);
  if (renamesLiteral !== null) parts.push(`  renames: ${renamesLiteral},`);
  if (entries.length > 0) parts.push(`  tables: {\n${entries.map((e) => e.text).join("\n")}\n  },`);
  const body = parts.length > 0 ? `{\n${parts.join("\n")}\n}` : "{}";

  const rowImports = [...holeTables]
    .map(rowName)
    .sort(byName)
    .map((n) => `type ${n}`);
  const importList = ["defineMigration", ...rowImports].join(", ");

  return `${SCAFFOLD_HEADER}import { ${importList} } from "./meta/${stem}.types.ts";\n\nexport default defineMigration(${body});\n`;
}

// -- the types companion ------------------------------------------------------

function renderTypes(
  pre: SchemaSnapshot,
  target: SchemaSnapshot,
  normalizedRenames: { tables: Record<string, string> },
): string {
  const { pre: preTables, target: targetTables } = realTables(pre, target);
  const oldNameOf = new Map<string, string>(); // target name -> stored name
  for (const [oldT, newT] of Object.entries(normalizedRenames.tables)) oldNameOf.set(newT, oldT);
  const targetSet = new Set(targetTables);

  const lines: string[] = [TYPES_HEADER];
  lines.push('import { defineMigration as defineMigrationRuntime } from "@dbzz/server";');
  lines.push('import type { Renames } from "@dbzz/server";');
  lines.push("");

  lines.push("/** Rows as they existed BEFORE this migration (the recorded pre-snapshot). */");
  for (const t of preTables) lines.push(`type ${beforeName(t)} = ${renderRow(pre.tables[t]!)};`);
  lines.push("");
  lines.push("/** Rows of the NEW schema this migration targets. */");
  for (const t of targetTables) lines.push(`export type ${rowName(t)} = ${renderRow(target.tables[t]!)};`);
  lines.push("");
  lines.push("/** Insert shapes for the NEW schema (primary key omitted, nullable columns optional). */");
  for (const t of targetTables) lines.push(`type ${insertName(t)} = ${renderInsert(target.tables[t]!)};`);
  lines.push("");

  lines.push("interface MigrationBeforeTable<Row> {");
  lines.push("  get(id: bigint): Promise<Row | null>;");
  lines.push("  scan(): AsyncIterableIterator<Row>;");
  lines.push("}");
  lines.push("");

  lines.push("interface MigrationInserts {");
  for (const t of targetTables) lines.push(`  ${identKey(t)}: ${insertName(t)};`);
  lines.push("}");
  lines.push("");

  lines.push("interface MigrationContext {");
  lines.push("  readonly before: {");
  for (const t of preTables) lines.push(`    ${identKey(t)}: MigrationBeforeTable<${beforeName(t)}>;`);
  lines.push("  };");
  lines.push("  insert<Table extends keyof MigrationInserts>(table: Table, row: MigrationInserts[Table]): void;");
  lines.push("}");
  lines.push("");

  // The specialized parameter type: every surviving table a transform
  // `(old, ctx) => new | null | Promise<new | null>` (NO void — a hole with a
  // declared return type must not typecheck), every dropped table a salvage or
  // `null`.
  const slots: { key: string; text: string }[] = [];
  for (const newName of targetTables) {
    const oldName = oldNameOf.get(newName) ?? newName;
    if (pre.tables[oldName]?.kind !== "table") continue; // newly added: no old rows to transform
    slots.push({
      key: newName,
      text: `    ${identKey(newName)}?: (row: ${beforeName(oldName)}, ctx: MigrationContext) => ${rowName(newName)} | null | Promise<${rowName(newName)} | null>;`,
    });
  }
  for (const oldName of preTables) {
    const newName = normalizedRenames.tables[oldName] ?? oldName;
    if (targetSet.has(newName)) continue; // survived
    slots.push({
      key: oldName,
      text: `    ${identKey(oldName)}?: null | ((row: ${beforeName(oldName)}, ctx: MigrationContext) => void | Promise<void>);`,
    });
  }
  slots.sort((a, b) => byName(a.key, b.key));

  lines.push("interface MigrationDefinition {");
  lines.push("  renames?: Renames;");
  if (slots.length > 0) {
    lines.push("  tables?: {");
    for (const slot of slots) lines.push(slot.text);
    lines.push("  };");
  }
  lines.push("}");
  lines.push("");

  lines.push("/** The runtime `defineMigration`, typed for exactly this migration step. */");
  lines.push("export const defineMigration = defineMigrationRuntime as unknown as (");
  lines.push("  migration: MigrationDefinition,");
  lines.push(") => MigrationDefinition;");
  lines.push("");

  return lines.join("\n");
}
