/* eslint-disable */
// Generated by `acker codegen`. Do not edit manually.

import {
  mcp as mcpGeneric,
  channel as channelGeneric,
  realtime as realtimeGeneric,
  mcpAuth as mcpAuthGeneric,
  mutation as mutationGeneric,
  procedure as procedureGeneric,
  query as queryGeneric,
  sseProcedure as sseProcedureGeneric,
} from "@ackerdb/server";
import type {
  AppSchema,
  ChannelBuilder,
  DbReader,
  DbWriter,
  McpAuthBuilder,
  McpBuilder,
  MutationBuilder,
  MutationCtx as GenericMutationCtx,
  ProcedureBuilder,
  ProcedureCtx as GenericProcedureCtx,
  QueryBuilder,
  RealtimeBuilder,
  QueryCtx as GenericQueryCtx,
  SseBuilder,
  SseCtx as GenericSseCtx,
  SystemCtx as GenericSystemCtx,
} from "@ackerdb/server";
import type app from "../../../app/server/app.ts";

export type Schema = AppSchema<typeof app>;
type Capabilities = Readonly<Record<never, never>>;

export const query = queryGeneric as QueryBuilder<Schema, Capabilities>;
export const channel = channelGeneric as ChannelBuilder<Schema>;
export const realtime = realtimeGeneric as unknown as RealtimeBuilder<Schema, Capabilities, Capabilities>;
export const mutation = mutationGeneric as MutationBuilder<Schema, Capabilities>;
export const procedure = procedureGeneric as ProcedureBuilder<Schema, Capabilities, Capabilities>;
export const sseProcedure = sseProcedureGeneric as SseBuilder<Schema, Capabilities, Capabilities>;
export const mcp = mcpGeneric as McpBuilder<Schema>;
export const mcpAuth = mcpAuthGeneric as McpAuthBuilder<Schema>;

export type QueryCtx = GenericQueryCtx<Schema, Capabilities>;
export type MutationCtx = GenericMutationCtx<Schema, Capabilities>;
export type ProcedureCtx = GenericProcedureCtx<Schema, Capabilities, Capabilities>;
export type SseCtx = GenericSseCtx<Schema, Capabilities, Capabilities>;
export type SystemCtx = GenericSystemCtx<Schema, Capabilities, Capabilities>;
export type DatabaseReader = DbReader<Schema>;
export type DatabaseWriter = DbWriter<Schema>;
