/* eslint-disable */
// Generated by `acker codegen`. Do not edit manually.

import {
  mcp as mcpGeneric,
  channel as channelGeneric,
  realtime as realtimeGeneric,
  mcpAuth as mcpAuthGeneric,
  mutation as mutationGeneric,
  procedure as procedureGeneric,
  query as queryGeneric,
  service as serviceGeneric,
  sseProcedure as sseProcedureGeneric,
} from "@ackerdb/server";
import type {
  AppPluginCapabilities,
  AppSchema,
  ChannelBuilder,
  DbReader,
  DbWriter,
  McpAuthBuilder,
  McpBuilder,
  MutationBuilder,
  MutationCtx as GenericMutationCtx,
  ProcedureBuilder,
  ProcedureCtx as GenericProcedureCtx,
  QueryBuilder,
  RealtimeBuilder,
  QueryCtx as GenericQueryCtx,
  ServiceBuilder,
  ServiceContext as GenericServiceContext,
  SseBuilder,
  SseCtx as GenericSseCtx,
  SystemCtx as GenericSystemCtx,
} from "@ackerdb/server";
import type app from "../../../app/server/app.ts";

export type Schema = AppSchema<typeof app>;
type QueryPlugins = AppPluginCapabilities<typeof app, "query">;
type MutationPlugins = AppPluginCapabilities<typeof app, "mutation">;
type ProcedurePlugins = AppPluginCapabilities<typeof app, "procedure">;

export const query = queryGeneric as QueryBuilder<Schema, QueryPlugins>;
export const channel = channelGeneric as ChannelBuilder<Schema>;
export const realtime = realtimeGeneric as unknown as RealtimeBuilder<Schema, ProcedurePlugins, MutationPlugins>;
export const mutation = mutationGeneric as MutationBuilder<Schema, MutationPlugins>;
export const procedure = procedureGeneric as ProcedureBuilder<Schema, ProcedurePlugins, MutationPlugins>;
export const sseProcedure = sseProcedureGeneric as SseBuilder<Schema, ProcedurePlugins, MutationPlugins>;
export const service = serviceGeneric as ServiceBuilder<Schema, ProcedurePlugins, MutationPlugins>;
export const mcp = mcpGeneric as McpBuilder<Schema>;
export const mcpAuth = mcpAuthGeneric as McpAuthBuilder<Schema>;

export type QueryCtx = GenericQueryCtx<Schema, QueryPlugins>;
export type MutationCtx = GenericMutationCtx<Schema, MutationPlugins>;
export type ProcedureCtx = GenericProcedureCtx<Schema, ProcedurePlugins, MutationPlugins>;
export type SseCtx = GenericSseCtx<Schema, ProcedurePlugins, MutationPlugins>;
export type SystemCtx = GenericSystemCtx<Schema, ProcedurePlugins, MutationPlugins>;
export type ServiceCtx = GenericServiceContext<SystemCtx>;
export type DatabaseReader = DbReader<Schema>;
export type DatabaseWriter = DbWriter<Schema>;
