/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminTablesRouteImport } from './routes/_admin/tables'
import { Route as AdminOrdersRouteImport } from './routes/_admin/orders'
import { Route as AdminMenuRouteImport } from './routes/_admin/menu'
import { Route as AdminKitchenRouteImport } from './routes/_admin/kitchen'
import { Route as AdminGuestsRouteImport } from './routes/_admin/guests'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuestsRoute = AdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/guests': typeof AdminGuestsRoute
  '/kitchen': typeof AdminKitchenRoute
  '/menu': typeof AdminMenuRoute
  '/orders': typeof AdminOrdersRoute
  '/tables': typeof AdminTablesRoute
}
export interface FileRoutesByTo {
  '/guests': typeof AdminGuestsRoute
  '/kitchen': typeof AdminKitchenRoute
  '/menu': typeof AdminMenuRoute
  '/orders': typeof AdminOrdersRoute
  '/tables': typeof AdminTablesRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/guests': typeof AdminGuestsRoute
  '/_admin/kitchen': typeof AdminKitchenRoute
  '/_admin/menu': typeof AdminMenuRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_admin/tables': typeof AdminTablesRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guests' | '/kitchen' | '/menu' | '/orders' | '/tables'
  fileRoutesByTo: FileRoutesByTo
  to: '/guests' | '/kitchen' | '/menu' | '/orders' | '/tables' | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/guests'
    | '/_admin/kitchen'
    | '/_admin/menu'
    | '/_admin/orders'
    | '/_admin/tables'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tables': {
      id: '/_admin/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/menu': {
      id: '/_admin/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/kitchen': {
      id: '/_admin/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/guests': {
      id: '/_admin/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AdminGuestsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminGuestsRoute: typeof AdminGuestsRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminTablesRoute: typeof AdminTablesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGuestsRoute: AdminGuestsRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminTablesRoute: AdminTablesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
